---
- name: Deploy WAR to Tomcat
  hosts: all
  become: yes
  
  tasks:
    - name: Stop Tomcat
      systemd:
        name: tomcat
        state: stopped
      ignore_errors: yes

    - name: Remove old deployment
      shell: rm -rf /opt/tomcat/webapps/sample-java-webapp*
      ignore_errors: yes

    - name: Download WAR from Nexus
      get_url:
        url: "http://172.31.47.6:8081/repository/maven-releases/com/demo/sample-java-webapp/1.0.0/sample-java-webapp-1.0.0.war"
        dest: "/opt/tomcat/webapps/sample-java-webapp.war"
        url_username: admin
        url_password: admin123
        force: yes

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started

    - name: Wait for Tomcat
      wait_for:
        port: 8080
        delay: 10
