---
- name: Deploy WAR to Tomcat
  hosts: tomcat
  become: yes
  
  tasks:
    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh
      ignore_errors: yes

    - name: Wait 10 seconds
      pause:
        seconds: 10

    - name: Remove old WAR and folder
      shell: |
        rm -rf /opt/tomcat/webapps/{{ app_name }}
        rm -f /opt/tomcat/webapps/{{ app_name }}.war

    - name: Copy WAR file from Jenkins
      copy:
        src: "{{ war_file }}"
        dest: /opt/tomcat/webapps/{{ app_name }}.war

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh

    - name: Wait for deployment
      pause:
        seconds: 15

    - name: Show success message
      debug:
        msg: "App deployed at http://172.31.33.205:8080/{{ app_name }}"
